import os
from stat import S_IXUSR, S_IXGRP, S_IXOTH

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(ROOT, "zappy_ai")

LAUNCHER = """#!/bin/sh
# Auto-generated by ia/compile.py — do not edit.
here="$(cd "$(dirname "$0")" && pwd)"
exec python3 "$here/ia/zappy_ai.py" "$@"
"""

with open(TARGET, "w") as f:
    f.write(LAUNCHER)

mode = os.stat(TARGET).st_mode
os.chmod(TARGET, mode | S_IXUSR | S_IXGRP | S_IXOTH)
